### PR TITLE
upgrade-deps script

### PR DESCRIPTION
**Pull request by serl**
This script could help for #7.

The missing parts are:

- automatically create a push request (sadly, seems not so trivial)
- run tests (should be done on the mentioned push request)

### CODE REVIEW

**Comment by volodymyrlut** [comment]
Maybe we should better consider using the tool, you've sent me on TG?

**Comment by serl** [comment]
Yup, [dependencies.io](https://www.dependencies.io/) looks really good!

Anyway, in order to compare the results, this is what my script says right now:
```json
  "dependencies": {
    "body-parser": "^1.18.2",
    "dotenv": "^5.0.1",
    "express": "^4.16.2",
    "node-telegram-bot-api": "^0.30.0"
  }
```

**Review by volodymyrlut — APPROVED** [review]
Awesome thing.
I am setting up CircleCI integration for this.

**Comment by volodymyrlut** [comment]
@serl can you please show me a copy of your config.yml file?

**Pull request merged**
